### ISSUE TITLE
Scrollen und Gestensteuerung funktionieren nicht gleichzeitig

### ISSUE THREAD

**Issue by benedikt255** [benedikt255/VDIHackathon2020#3]
Wenn die Gestensteuerung aktiv ist, funktioniert scrollen auf Touchscreengeräten nicht mehr

**Comment by ufze** [comment]
Umgesetzter Lösungsvorschlag:
[https://stackoverflow.com/questions/41017202/vertical-scroll-is-not-working-with-hammerjs-and-angular2](https://stackoverflow.com/questions/41017202/vertical-scroll-is-not-working-with-hammerjs-and-angular2)
HammerJS unterscheidet 7 verschiedene Gesten, siehe hier: [https://hammerjs.github.io/api/](https://hammerjs.github.io/api/)
Davon habe ich durch einen Codeschnipsel in app.module.ts die beiden Gesten 'rotate' und 'pinch' deaktiviert, da diese im Konflikt zur Scrollfunktion stehen

`import { HAMMER_GESTURE_CONFIG, HammerGestureConfig } from '@angular/platform-browser';
export class MyHammerConfig extends HammerGestureConfig {
    overrides = <any> {
        'pinch': { enable: false },
        'rotate': { enable: false }
    }
}`

**Comment by benedikt255** [comment]
fixed
